# Lucid Service Mesh - Envoy Cluster Configuration
# File: infrastructure/service-mesh/sidecar/envoy/config/cluster.yaml
# Lines: ~250
# Purpose: Envoy cluster configuration for service mesh

version_info: "1"
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: local_service
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: local_service
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 8080
  health_checks:
  - timeout: 1s
    interval: 10s
    unhealthy_threshold: 3
    healthy_threshold: 2
    http_health_check:
      path: "/health"
      expected_statuses:
      - start: 200
        end: 299
  circuit_breakers:
    thresholds:
    - priority: DEFAULT
      max_connections: 1000
      max_pending_requests: 1000
      max_requests: 1000
      max_retries: 3
    - priority: HIGH
      max_connections: 2000
      max_pending_requests: 2000
      max_requests: 2000
      max_retries: 3

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: service_mesh
  connect_timeout: 0.25s
  type: EDS
  lb_policy: ROUND_ROBIN
  eds_cluster_config:
    eds_config:
      api_config_source:
        api_type: GRPC
        grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster
  health_checks:
  - timeout: 1s
    interval: 10s
    unhealthy_threshold: 3
    healthy_threshold: 2
    http_health_check:
      path: "/health"
  circuit_breakers:
    thresholds:
    - priority: DEFAULT
      max_connections: 2000
      max_pending_requests: 2000
      max_requests: 2000
      max_retries: 3

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: xds_cluster
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: xds_cluster
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: service-mesh-controller
              port_value: 8600

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: consul
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: consul
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: consul
              port_value: 8500

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: api_gateway
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: api_gateway
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: api-gateway
              port_value: 8080
  health_checks:
  - timeout: 1s
    interval: 10s
    unhealthy_threshold: 3
    healthy_threshold: 2
    http_health_check:
      path: "/health"

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: blockchain_core
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: blockchain_core
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: blockchain-core
              port_value: 8084
  health_checks:
  - timeout: 1s
    interval: 10s
    unhealthy_threshold: 3
    healthy_threshold: 2
    http_health_check:
      path: "/health"

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: session_management
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: session_management
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: session-api
              port_value: 8087
  health_checks:
  - timeout: 1s
    interval: 10s
    unhealthy_threshold: 3
    healthy_threshold: 2
    http_health_check:
      path: "/health"

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: node_management
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: node_management
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: node-management
              port_value: 8095
  health_checks:
  - timeout: 1s
    interval: 10s
    unhealthy_threshold: 3
    healthy_threshold: 2
    http_health_check:
      path: "/health"

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: auth_service
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: auth_service
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: auth-service
              port_value: 8089
  health_checks:
  - timeout: 1s
    interval: 10s
    unhealthy_threshold: 3
    healthy_threshold: 2
    http_health_check:
      path: "/health"

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: health_check_cluster
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: health_check_cluster
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 8080

- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: stats_cluster
  connect_timeout: 0.25s
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: stats_cluster
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 8080
