# Lucid Services Docker Compose for Raspberry Pi
# Uses pre-built pickme/lucid-* images
# MUST RUN ON PI CONSOLE - NOT FROM WINDOWS

version: '3.8'

services:
  # Foundation Services
  lucid-mongodb:
    image: pickme/lucid-mongodb:latest-arm64
    container_name: lucid-mongodb
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - lucid-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lucid
      - MONGO_INITDB_ROOT_PASSWORD=lucid
      - MONGO_INITDB_DATABASE=lucid
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-redis:
    image: pickme/lucid-redis:latest-arm64
    container_name: lucid-redis
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lucid-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-elasticsearch:
    image: pickme/lucid-elasticsearch:latest-arm64
    container_name: lucid-elasticsearch
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - lucid-network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Core Services
  lucid-api-gateway:
    image: pickme/lucid-api-gateway:latest-arm64
    container_name: lucid-api-gateway
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8080:8080"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-blockchain-engine:
    image: pickme/lucid-blockchain-engine:latest-arm64
    container_name: lucid-blockchain-engine
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8084:8084"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-session-anchoring:
    image: pickme/lucid-session-anchoring:latest-arm64
    container_name: lucid-session-anchoring
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8085:8085"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-block-manager:
    image: pickme/lucid-block-manager:latest-arm64
    container_name: lucid-block-manager
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8086:8086"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-data-chain:
    image: pickme/lucid-data-chain:latest-arm64
    container_name: lucid-data-chain
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8087:8087"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-service-mesh-controller:
    image: pickme/lucid-service-mesh-controller:latest-arm64
    container_name: lucid-service-mesh-controller
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8088:8088"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application Services
  lucid-session-pipeline:
    image: pickme/lucid-session-pipeline:latest-arm64
    container_name: lucid-session-pipeline
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8089:8089"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-session-recorder:
    image: pickme/lucid-session-recorder:latest-arm64
    container_name: lucid-session-recorder
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8090:8090"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-chunk-processor:
    image: pickme/lucid-chunk-processor:latest-arm64
    container_name: lucid-chunk-processor
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8091:8091"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-session-storage:
    image: pickme/lucid-session-storage:latest-arm64
    container_name: lucid-session-storage
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8092:8092"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-session-api:
    image: pickme/lucid-session-api:latest-arm64
    container_name: lucid-session-api
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8093:8093"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RDP Services
  lucid-rdp-server-manager:
    image: pickme/lucid-rdp-server-manager:latest-arm64
    container_name: lucid-rdp-server-manager
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "3389:3389"
      - "3350:3350"
      - "3351:3351"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3389/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-xrdp-integration:
    image: pickme/lucid-xrdp-integration:latest-arm64
    container_name: lucid-xrdp-integration
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8094:8094"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8094/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-resource-monitor:
    image: pickme/lucid-resource-monitor:latest-arm64
    container_name: lucid-resource-monitor
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8095:8095"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node Management
  lucid-node-management:
    image: pickme/lucid-node-management:latest-arm64
    container_name: lucid-node-management
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8096:8096"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Support Services
  lucid-admin-interface:
    image: pickme/lucid-admin-interface:latest-arm64
    container_name: lucid-admin-interface
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8097:8097"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8097/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # TRON Services
  lucid-tron-client:
    image: pickme/lucid-tron-client:latest-arm64
    container_name: lucid-tron-client
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8098:8098"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8098/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-payout-router:
    image: pickme/lucid-payout-router:latest-arm64
    container_name: lucid-payout-router
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8099:8099"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-wallet-manager:
    image: pickme/lucid-wallet-manager:latest-arm64
    container_name: lucid-wallet-manager
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8100:8100"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-usdt-manager:
    image: pickme/lucid-usdt-manager:latest-arm64
    container_name: lucid-usdt-manager
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8101:8101"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8101/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-trx-staking:
    image: pickme/lucid-trx-staking:latest-arm64
    container_name: lucid-trx-staking
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8102:8102"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8102/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lucid-payment-gateway:
    image: pickme/lucid-payment-gateway:latest-arm64
    container_name: lucid-payment-gateway
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8103:8103"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8103/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # GUI Services
  lucid-gui:
    image: pickme/lucid-gui:latest-arm64
    container_name: lucid-gui
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8083:8083"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Auth Service
  lucid-auth-service:
    image: pickme/lucid-auth-service:latest-arm64
    container_name: lucid-auth-service
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8089:8089"
    networks:
      - lucid-network
    depends_on:
      - lucid-mongodb
      - lucid-redis
    environment:
      - MONGODB_URI=mongodb://lucid:lucid@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lucid-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  mongodb_data:
  redis_data:
  elasticsearch_data:
