apiVersion: v1
kind: Secret
metadata:
  name: lucid-runtime-secrets
  namespace: lucid
type: Opaque
stringData:
  MONGODB_PASSWORD: RzENjKTj4G1V2Ohfd8HdsbaiBpzOo97x
  REDIS_PASSWORD: CAafNePARt5eqivBsZmsXF8yvR2bJ4FJ
  JWT_SECRET_KEY: w+p9+dr7IeOhTRlj6f9R7UqH1q9bCeZii2h4ZjgTBUo=
  ENCRYPTION_KEY: cb02b88cb193d003201d39e918982f55f117c188f4a2cf61c288bf9febce4e71
  SESSION_SECRET: P1zO4ICyD3OQ7K47i0vS88poz3dPl65y
  TRON_PRIVATE_KEY: 5005c91bc985f9d115559b4917951e059771369a3d9bd802999fa774f02dd5b7c2932cef04d96570333ee0
  TRON_API_KEY: 32b1dd8c-e633-481a-9fd3-9263a17196ff
  ELASTICSEARCH_PASSWORD: L8PD6BchI8dFCdPxXKriPJsC7nvhjfN
  TOR_PASSWORD: ypfYDuIrN7XuG5RKMmiMT0mHTlgoPgNcpw2DZOnNaA
  TOR_CONTROL_PASSWORD: Bkni9GoqLh6VZ8JdSiKJFHrw1oMoLpc3Z3kUJQ
