# Prometheus configuration for Lucid RDP monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'lucid-rdp'
    environment: 'production'

# Rule files
rule_files:
  - "lucid_rules.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # Docker daemon metrics
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['docker-daemon:9323']
    scrape_interval: 15s
    metrics_path: /metrics

  # Lucid RDP services (distroless-compatible)
  - job_name: 'lucid-admin-ui'
    static_configs:
      - targets: ['admin-ui:3000']
    metrics_path: /api/metrics
    scrape_interval: 30s
    metric_relabel_configs:
      # Ensure distroless-compatible metrics only
      - source_labels: [__name__]
        regex: 'http_requests_total|http_request_duration_seconds|process_cpu_seconds_total|process_resident_memory_bytes'
        action: keep

  - job_name: 'lucid-blockchain'
    static_configs:
      - targets: ['blockchain-core:8545']
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      # Ensure distroless-compatible metrics only
      - source_labels: [__name__]
        regex: 'blockchain_.*|http_requests_total|process_cpu_seconds_total|process_resident_memory_bytes'
        action: keep

  - job_name: 'lucid-payment-service'
    static_configs:
      - targets: ['payment-service:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      # Ensure payment-only metrics (TRON isolation)
      - source_labels: [__name__]
        regex: 'payment_.*|tron_.*|http_requests_total|process_cpu_seconds_total|process_resident_memory_bytes'
        action: keep

  - job_name: 'lucid-sessions'
    static_configs:
      - targets: ['sessions:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-storage'
    static_configs:
      - targets: ['storage:8081']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-vm'
    static_configs:
      - targets: ['vm:8082']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-gui'
    static_configs:
      - targets: ['gui:8083']
    metrics_path: /metrics
    scrape_interval: 30s

  # MongoDB metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: /metrics
    scrape_interval: 30s

  # Tor metrics
  - job_name: 'tor'
    static_configs:
      - targets: ['tor-proxy:9051']
    metrics_path: /metrics
    scrape_interval: 60s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: /metrics
    scrape_interval: 30s

  # cAdvisor for container metrics (distroless-compatible)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    metric_relabel_configs:
      # Filter out distroless-specific metrics
      - source_labels: [__name__]
        regex: 'container_spec_memory_limit_bytes|container_spec_cpu_quota'
        action: drop

  # Blackbox exporter for external checks
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://localhost:3000  # Admin UI
        - http://localhost:8080  # API Gateway
        - http://localhost:8545  # Blockchain RPC
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Tor connectivity checks
  - job_name: 'tor-connectivity'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - localhost:9050  # Tor SOCKS
        - localhost:9051  # Tor Control
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Payment service connectivity checks
  - job_name: 'payment-connectivity'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://localhost:8080/health  # Payment service health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Storage configuration
# Note: Retention settings should be configured via command line flags
# --storage.tsdb.retention.time=30d

# Remote write configuration (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"
