# LUCID SESSION PIPELINE - Distroless Deployment
# Phase 2: Session Pipeline Services (Chunker, Encryptor, Merkle, Orchestrator, Auth)
# Aligned with LUCID_DISTROLESS_BUILD_GUIDE.md Phase 3.2



services:
  session-chunker:
    image: pickme/lucid-session-chunker:latest-arm64
    container_name: session-chunker
    restart: unless-stopped
    networks:
      - lucid-pi-network
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - CHUNK_SIZE_MB=8
      - COMPRESSION_LEVEL=3
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/data/sessions:/data/sessions:rw
      - /mnt/myssd/Lucid/logs/session-chunker:/app/logs:rw
      - session-chunker-cache:/tmp/chunker
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=session-chunker"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

  session-encryptor:
    image: pickme/lucid-session-encryptor:latest-arm64
    container_name: session-encryptor
    restart: unless-stopped
    networks:
      - lucid-pi-network
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - ENCRYPTION_ALGORITHM=XChaCha20-Poly1305
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/data/sessions:/data/sessions:ro
      - /mnt/myssd/Lucid/data/encrypted:/data/encrypted:rw
      - /mnt/myssd/Lucid/logs/session-encryptor:/app/logs:rw
      - session-encryptor-cache:/tmp/encryptor
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=session-encryptor"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

  merkle-builder:
    image: pickme/lucid-merkle-builder:latest-arm64
    container_name: merkle-builder
    restart: unless-stopped
    networks:
      - lucid-pi-network
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - MERKLE_ALGORITHM=BLAKE3
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/data/encrypted:/data/encrypted:ro
      - /mnt/myssd/Lucid/data/merkle:/data/merkle:rw
      - /mnt/myssd/Lucid/logs/merkle-builder:/app/logs:rw
      - merkle-builder-cache:/tmp/merkle
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=merkle-builder"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

  session-orchestrator:
    image: pickme/lucid-session-orchestrator:latest-arm64
    container_name: session-orchestrator
    restart: unless-stopped
    networks:
      - lucid-pi-network
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - CHUNKER_URL=http://session-chunker:8090
      - ENCRYPTOR_URL=http://session-encryptor:8091
      - MERKLE_URL=http://merkle-builder:8092
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/data/sessions:/data/sessions:rw
      - /mnt/myssd/Lucid/data/encrypted:/data/encrypted:ro
      - /mnt/myssd/Lucid/data/merkle:/data/merkle:ro
      - /mnt/myssd/Lucid/logs/session-orchestrator:/app/logs:rw
      - session-orchestrator-cache:/tmp/orchestrator
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=session-orchestrator"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

  authentication_service:
    image: pickme/lucid-auth-service:latest-arm64
    container_name: authentication-service
    restart: unless-stopped
    networks:
      - lucid-pi-network
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - AUTH_SERVICE_PORT=8094
      - TRON_NETWORK=shasta
      - TRON_RPC_URL=https://api.shasta.trongrid.io
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/data/auth:/data/auth:rw
      - /mnt/myssd/Lucid/logs/authentication-service:/app/logs:rw
      - authentication-service-cache:/tmp/auth
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=authentication-service"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

volumes:
  session-chunker-cache:
    driver: local
    name: lucid-session-chunker-cache
  session-encryptor-cache:
    driver: local
    name: lucid-session-encryptor-cache
  merkle-builder-cache:
    driver: local
    name: lucid-merkle-builder-cache
  session-orchestrator-cache:
    driver: local
    name: lucid-session-orchestrator-cache
  authentication-service-cache:
    driver: local
    name: lucid-authentication-service-cache

networks:
  lucid-pi-network:
    external: true
    name: lucid-pi-network