# LUCID SESSION PIPELINE - Distroless Deployment
# Phase 2: Session Pipeline Services (Chunker, Encryptor, Merkle, Orchestrator, Auth)
# Aligned with essentials.md Phase 3 and service-ip-configuration.md
# Project Root: /mnt/myssd/Lucid/Lucid/

services:
  lucid-session-chunker:
    image: pickme/lucid-session-chunker:latest-arm64
    container_name: lucid-session-chunker
    hostname: lucid-session-chunker
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.application
      - ../../sessions/core/.env.chunker
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - PROJECT_ROOT=/mnt/myssd/Lucid/Lucid
      - CHUNK_SIZE_MB=8
      - COMPRESSION_LEVEL=3
      - CHUNKER_PORT=8090
      - MONGODB_URI=mongodb://lucid:${MONGODB_PASSWORD}@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
      - SESSION_CHUNK_SIZE=10485760
      - SESSION_COMPRESSION_LEVEL=6
      - CHUNKER_URL=http://lucid-session-chunker:8090
      - API_GATEWAY_URL=http://lucid-api-gateway:8080
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/Lucid/data/sessions:/data/sessions:rw
      - /mnt/myssd/Lucid/Lucid/logs/session-chunker:/app/logs:rw
      - session-chunker-cache:/tmp/chunker
    networks:
      lucid-pi-network:
        ipv4_address: 172.20.0.20
    depends_on:
      lucid-mongodb:
        condition: service_healthy
      lucid-redis:
        condition: service_healthy
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8090/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'
    labels:
      - "lucid.service=session-chunker"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

  lucid-session-encryptor:
    image: pickme/lucid-session-encryptor:latest-arm64
    container_name: lucid-session-encryptor
    hostname: lucid-session-encryptor
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.application
      - ../../sessions/encryption/.env.encryptor
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - PROJECT_ROOT=/mnt/myssd/Lucid/Lucid
      - ENCRYPTION_ALGORITHM=XChaCha20-Poly1305
      - ENCRYPTOR_PORT=8091
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - MONGODB_URI=mongodb://lucid:${MONGODB_PASSWORD}@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
      - ENCRYPTOR_URL=http://lucid-session-encryptor:8091
      - API_GATEWAY_URL=http://lucid-api-gateway:8080
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/Lucid/data/sessions:/data/sessions:ro
      - /mnt/myssd/Lucid/Lucid/data/encrypted:/data/encrypted:rw
      - /mnt/myssd/Lucid/Lucid/logs/session-encryptor:/app/logs:rw
      - session-encryptor-cache:/tmp/encryptor
    networks:
      lucid-pi-network:
        ipv4_address: 172.20.0.20
    depends_on:
      lucid-session-chunker:
        condition: service_healthy
      lucid-mongodb:
        condition: service_healthy
      lucid-redis:
        condition: service_healthy
    ports:
      - "8091:8091"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8091/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'
    labels:
      - "lucid.service=session-encryptor"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

  lucid-merkle-builder:
    image: pickme/lucid-merkle-builder:latest-arm64
    container_name: lucid-merkle-builder
    hostname: lucid-merkle-builder
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.application
      - ../../sessions/core/.env.merkle_builder
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - PROJECT_ROOT=/mnt/myssd/Lucid/Lucid
      - MERKLE_ALGORITHM=BLAKE3
      - MERKLE_PORT=8092
      - MONGODB_URI=mongodb://lucid:${MONGODB_PASSWORD}@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
      - MERKLE_URL=http://lucid-merkle-builder:8092
      - API_GATEWAY_URL=http://lucid-api-gateway:8080
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/Lucid/data/encrypted:/data/encrypted:ro
      - /mnt/myssd/Lucid/Lucid/data/merkle:/data/merkle:rw
      - /mnt/myssd/Lucid/Lucid/logs/merkle-builder:/app/logs:rw
      - merkle-builder-cache:/tmp/merkle
    networks:
      lucid-pi-network:
        ipv4_address: 172.20.0.20
    depends_on:
      lucid-session-encryptor:
        condition: service_healthy
      lucid-mongodb:
        condition: service_healthy
      lucid-redis:
        condition: service_healthy
    ports:
      - "8092:8092"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8092/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'
    labels:
      - "lucid.service=merkle-builder"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

  lucid-session-orchestrator:
    image: pickme/lucid-session-orchestrator:latest-arm64
    container_name: lucid-session-orchestrator
    hostname: lucid-session-orchestrator
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.application
      - ../../sessions/core/.env.orchestrator
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - PROJECT_ROOT=/mnt/myssd/Lucid/Lucid
      - CHUNKER_URL=http://lucid-session-chunker:8090
      - ENCRYPTOR_URL=http://lucid-session-encryptor:8091
      - MERKLE_URL=http://lucid-merkle-builder:8092
      - ORCHESTRATOR_PORT=8093
      - MONGODB_URI=mongodb://lucid:${MONGODB_PASSWORD}@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
      - SESSION_PIPELINE_URL=http://lucid-session-orchestrator:8093
      - API_GATEWAY_URL=http://lucid-api-gateway:8080
      - SESSION_TIMEOUT=1800
      - SESSION_PIPELINE_STATES=recording,chunk_generation,compression,encryption,merkle_building,storage
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/Lucid/data/sessions:/data/sessions:rw
      - /mnt/myssd/Lucid/Lucid/data/encrypted:/data/encrypted:ro
      - /mnt/myssd/Lucid/Lucid/data/merkle:/data/merkle:ro
      - /mnt/myssd/Lucid/Lucid/logs/session-orchestrator:/app/logs:rw
      - session-orchestrator-cache:/tmp/orchestrator
    networks:
      lucid-pi-network:
        ipv4_address: 172.20.0.20
    depends_on:
      lucid-session-chunker:
        condition: service_healthy
      lucid-session-encryptor:
        condition: service_healthy
      lucid-merkle-builder:
        condition: service_healthy
      lucid-mongodb:
        condition: service_healthy
      lucid-redis:
        condition: service_healthy
    ports:
      - "8093:8093"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8093/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'
    labels:
      - "lucid.service=session-orchestrator"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

  lucid-auth-service:
    image: pickme/lucid-auth-service:latest-arm64
    container_name: lucid-auth-service
    hostname: lucid-auth-service
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.authentication
    environment:
      - LUCID_ENV=production
      - LUCID_PLATFORM=arm64
      - PROJECT_ROOT=/mnt/myssd/Lucid/Lucid
      - AUTH_SERVICE_PORT=8089
      - AUTH_SERVICE_URL=http://lucid-auth-service:8089
      - AUTH_SERVICE_HOST=172.20.0.14
      - MONGODB_URI=mongodb://lucid:${MONGODB_PASSWORD}@lucid-mongodb:27017/lucid?authSource=admin
      - REDIS_URL=redis://lucid-redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=15
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
      - API_GATEWAY_URL=http://lucid-api-gateway:8080
      - TRON_NETWORK=mainnet
      - TRON_RPC_URL=https://api.trongrid.io
    user: "65532:65532"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - /mnt/myssd/Lucid/Lucid/data/auth:/data/auth:rw
      - /mnt/myssd/Lucid/Lucid/logs/auth-service:/app/logs:rw
      - authentication-service-cache:/tmp/auth
    networks:
      lucid-pi-network:
        ipv4_address: 172.20.0.14
    depends_on:
      lucid-mongodb:
        condition: service_healthy
      lucid-redis:
        condition: service_healthy
    ports:
      - "8089:8089"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8089/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'
    labels:
      - "lucid.service=authentication-service"
      - "lucid.type=distroless"
      - "lucid.platform=arm64"
      - "lucid.security=hardened"
      - "lucid.cluster=sessions"

volumes:
  session-chunker-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/myssd/Lucid/Lucid/data/cache/session-chunker
  session-encryptor-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/myssd/Lucid/Lucid/data/cache/session-encryptor
  merkle-builder-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/myssd/Lucid/Lucid/data/cache/merkle-builder
  session-orchestrator-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/myssd/Lucid/Lucid/data/cache/session-orchestrator
  authentication-service-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/myssd/Lucid/Lucid/data/cache/auth-service

networks:
  lucid-pi-network:
    external: true
    name: lucid-pi-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1