# LUCID SESSION PIPELINE - Distroless Deployment
# Phase 2: Session Pipeline Services (Chunker, Encryptor, Merkle, Orchestrator, Auth)
# Aligned with LUCID_DISTROLESS_BUILD_GUIDE.md Phase 3.2



services:
  session-chunker:
    image: pickme/lucid:session-chunker:latest
    container_name: session_chunker
    pull_policy: always
    environment:
      CHUNK_SIZE_MB: "8"
      COMPRESSION_LEVEL: "3"
      MONGODB_URL: "mongodb://lucid:lucid@lucid_mongo:27017/lucid"
    volumes:
      - sessions_data:/data/sessions
    networks:
      - lucid_core_net
    depends_on:
      - lucid_mongo
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8090/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'

  session-encryptor:
    image: pickme/lucid:session-encryptor:latest
    container_name: session_encryptor
    pull_policy: always
    environment:
      ENCRYPTION_ALGORITHM: "XChaCha20-Poly1305"
      MONGODB_URL: "mongodb://lucid:lucid@lucid_mongo:27017/lucid"
    volumes:
      - sessions_data:/data/sessions:ro
      - encrypted_data:/data/encrypted
    networks:
      - lucid_core_net
    depends_on:
      - session-chunker
    ports:
      - "8091:8091"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8091/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'

  merkle-builder:
    image: pickme/lucid:merkle-builder:latest
    container_name: merkle_builder
    pull_policy: always
    environment:
      MERKLE_ALGORITHM: "BLAKE3"
      MONGODB_URL: "mongodb://lucid:lucid@lucid_mongo:27017/lucid"
    volumes:
      - encrypted_data:/data/encrypted:ro
      - chain_data:/data/merkle
    networks:
      - lucid_core_net
    depends_on:
      - session-encryptor
    ports:
      - "8092:8092"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8092/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'

  session-orchestrator:
    image: pickme/lucid:session-orchestrator:latest
    container_name: session_orchestrator
    pull_policy: always
    environment:
      CHUNKER_URL: "http://session-chunker:8090"
      ENCRYPTOR_URL: "http://session-encryptor:8091"
      MERKLE_URL: "http://merkle-builder:8092"
    volumes:
      - sessions_data:/data/sessions
      - encrypted_data:/data/encrypted:ro
      - chain_data:/data/merkle:ro
    networks:
      - lucid_core_net
    depends_on:
      - merkle-builder
    ports:
      - "8093:8093"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8093/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'

  authentication_service:
    image: pickme/lucid:authentication:latest
    container_name: authentication_service
    pull_policy: always
    environment:
      AUTH_SERVICE_PORT: "8094"
      TRON_NETWORK: "shasta"
      TRON_RPC_URL: "https://api.shasta.trongrid.io"
      MONGODB_URL: "mongodb://lucid:lucid@lucid_mongo:27017/lucid"
    volumes:
      - chain_data:/data/auth
    networks:
      - lucid_core_net
    depends_on:
      - lucid_mongo
    ports:
      - "8094:8094"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8094/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  lucid_core_net:
    external: true

volumes:
  sessions_data:
  encrypted_data:
  chain_data: