apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucid-auth-service
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: lucid-blockchain
    lucid.service: auth-service
    lucid.type: foundation
    lucid.platform: arm64
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
      app.kubernetes.io/component: authentication
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/component: authentication
        app.kubernetes.io/part-of: lucid-blockchain
        lucid.service: auth-service
        lucid.type: foundation
        lucid.platform: arm64
    spec:
      hostname: lucid-auth-service
      containers:
      - name: auth-service
        image: pickme/lucid-auth-service:latest-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
          name: http
        env:
        - name: LUCID_ENV
          value: "production"
        - name: LUCID_PLATFORM
          value: "arm64"
        - name: PROJECT_ROOT
          value: "/mnt/myssd/Lucid/Lucid"
        - name: SERVICE_NAME
          value: "auth-service"
        - name: AUTH_SERVICE_PORT
          value: "8089"
        - name: AUTH_SERVICE_URL
          value: "http://lucid-auth-service:8089"
        - name: AUTH_SERVICE_HOST
          value: "172.20.0.14"
        - name: MONGODB_URI
          value: "mongodb://lucid:$(MONGODB_PASSWORD)@mongodb-service:27017/lucid?authSource=admin"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: REDIS_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MONGODB_PASSWORD
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_SECRET_KEY
        - name: JWT_REFRESH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_REFRESH_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_ALGORITHM
        - name: API_GATEWAY_URL
          value: "http://lucid-api-gateway:8080"
        volumeMounts:
        - name: auth-config
          mountPath: /app/config
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: auth-config
        configMap:
          name: auth-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: lucid-auth-service
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: lucid-blockchain
    lucid.service: auth-service
    lucid.type: foundation
    lucid.platform: arm64
spec:
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
  ports:
  - port: 8089
    targetPort: 8089
    name: http
  type: ClusterIP
  clusterIP: 172.20.0.14