apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
      app.kubernetes.io/component: authentication
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/component: authentication
        app.kubernetes.io/part-of: lucid-blockchain
    spec:
      containers:
      - name: auth-service
        image: lucid-auth-service:latest
        ports:
        - containerPort: 8089
          name: http
        env:
        - name: SERVICE_NAME
          value: "auth-service"
        - name: AUTH_PORT
          value: "8089"
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/lucid_auth"
        - name: REDIS_URL
          value: "redis://redis-service:6379/6"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_SECRET_KEY
        - name: JWT_REFRESH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_REFRESH_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_ALGORITHM
        volumeMounts:
        - name: auth-config
          mountPath: /app/config
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: auth-config
        configMap:
          name: auth-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
  ports:
  - port: 8089
    targetPort: 8089
    name: http
  type: ClusterIP
