# Prometheus configuration for Lucid RDP system - Step 48
# Comprehensive monitoring configuration for all services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'lucid-rdp'
    environment: 'production'
    region: 'global'

# Rule files
rule_files:
  - "../alerts.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations for all Lucid services
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # Docker daemon metrics
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['docker-daemon:9323']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # API Gateway (Cluster 01)
  - job_name: 'lucid-api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_requests_total|http_request_duration_seconds|api_gateway_.*|process_cpu_seconds_total|process_resident_memory_bytes'
        action: keep

  # Blockchain Core (Cluster 02)
  - job_name: 'lucid-blockchain-core'
    static_configs:
      - targets: ['blockchain-core:8084']
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'blockchain_.*|consensus_.*|block_.*|transaction_.*|http_requests_total|process_cpu_seconds_total|process_resident_memory_bytes'
        action: keep

  # Blockchain Anchoring Service
  - job_name: 'lucid-blockchain-anchoring'
    static_configs:
      - targets: ['blockchain-anchoring:8085']
    metrics_path: /metrics
    scrape_interval: 30s

  # Blockchain Manager Service
  - job_name: 'lucid-blockchain-manager'
    static_configs:
      - targets: ['blockchain-manager:8086']
    metrics_path: /metrics
    scrape_interval: 30s

  # Blockchain Data Service
  - job_name: 'lucid-blockchain-data'
    static_configs:
      - targets: ['blockchain-data:8087']
    metrics_path: /metrics
    scrape_interval: 30s

  # Session Management Pipeline (Cluster 03)
  - job_name: 'lucid-session-pipeline'
    static_configs:
      - targets: ['session-pipeline:8090']
    metrics_path: /metrics
    scrape_interval: 30s

  # Session Recorder Service
  - job_name: 'lucid-session-recorder'
    static_configs:
      - targets: ['session-recorder:8091']
    metrics_path: /metrics
    scrape_interval: 30s

  # Session Processor Service
  - job_name: 'lucid-session-processor'
    static_configs:
      - targets: ['session-processor:8092']
    metrics_path: /metrics
    scrape_interval: 30s

  # Session Storage Service
  - job_name: 'lucid-session-storage'
    static_configs:
      - targets: ['session-storage:8093']
    metrics_path: /metrics
    scrape_interval: 30s

  # Session API Service
  - job_name: 'lucid-session-api'
    static_configs:
      - targets: ['session-api:8094']
    metrics_path: /metrics
    scrape_interval: 30s

  # RDP Server Manager (Cluster 04)
  - job_name: 'lucid-rdp-server-manager'
    static_configs:
      - targets: ['rdp-server-manager:8095']
    metrics_path: /metrics
    scrape_interval: 30s

  # RDP XRDP Service
  - job_name: 'lucid-rdp-xrdp'
    static_configs:
      - targets: ['rdp-xrdp:8096']
    metrics_path: /metrics
    scrape_interval: 30s

  # RDP Session Controller
  - job_name: 'lucid-rdp-session-controller'
    static_configs:
      - targets: ['rdp-session-controller:8097']
    metrics_path: /metrics
    scrape_interval: 30s

  # RDP Resource Monitor
  - job_name: 'lucid-rdp-resource-monitor'
    static_configs:
      - targets: ['rdp-resource-monitor:8098']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Management (Cluster 05)
  - job_name: 'lucid-node-management'
    static_configs:
      - targets: ['node-management:8099']
    metrics_path: /metrics
    scrape_interval: 30s

  # Admin Interface (Cluster 06)
  - job_name: 'lucid-admin-interface'
    static_configs:
      - targets: ['admin-interface:8100']
    metrics_path: /metrics
    scrape_interval: 30s

  # TRON Payment Services (Cluster 07) - Isolated Network
  - job_name: 'lucid-tron-client'
    static_configs:
      - targets: ['tron-client:8101']
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'tron_.*|payment_.*|http_requests_total|process_cpu_seconds_total|process_resident_memory_bytes'
        action: keep

  - job_name: 'lucid-tron-payout-router'
    static_configs:
      - targets: ['tron-payout-router:8102']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-tron-wallet-manager'
    static_configs:
      - targets: ['tron-wallet-manager:8103']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-tron-usdt-manager'
    static_configs:
      - targets: ['tron-usdt-manager:8104']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-tron-staking'
    static_configs:
      - targets: ['tron-staking:8105']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-tron-payment-gateway'
    static_configs:
      - targets: ['tron-payment-gateway:8106']
    metrics_path: /metrics
    scrape_interval: 30s

  # Database Services (Cluster 08)
  - job_name: 'lucid-mongodb'
    static_configs:
      - targets: ['mongodb:27018']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-redis'
    static_configs:
      - targets: ['redis:6380']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'lucid-elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /metrics
    scrape_interval: 30s

  # Authentication Service (Cluster 09)
  - job_name: 'lucid-auth-service'
    static_configs:
      - targets: ['auth-service:8089']
    metrics_path: /metrics
    scrape_interval: 30s

  # Service Mesh Controller (Cluster 10)
  - job_name: 'lucid-service-mesh-controller'
    static_configs:
      - targets: ['service-mesh-controller:8107']
    metrics_path: /metrics
    scrape_interval: 30s

  # Additional monitoring endpoints for comprehensive coverage
  - job_name: 'lucid-health-checks'
    static_configs:
      - targets: 
        - 'api-gateway:8080/health'
        - 'blockchain-core:8084/health'
        - 'session-api:8094/health'
        - 'admin-interface:8100/health'
        - 'auth-service:8089/health'
        - 'node-management:8099/health'
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'health_check_status|service_uptime_seconds|service_response_time_seconds'
        action: keep

  # Blackbox exporter for external checks
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:8080/health
        - http://blockchain-core:8084/health
        - http://session-api:8094/health
        - http://admin-interface:8100/health
        - http://auth-service:8089/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Tor connectivity checks
  - job_name: 'tor-connectivity'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - localhost:9050  # Tor SOCKS
        - localhost:9051  # Tor Control
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Storage configuration
# Note: Retention settings should be configured via command line flags
# --storage.tsdb.retention.time=30d

# Remote write configuration (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"
