# Compose for Lucid (dev profile). Host editing in VS Code; runtime on Pi.
# .env required keys: ONION, COOKIE, HEX. Optional: BLOCK_ONION.

name: lucid-dev

x-default-env: &default-env
  LUCID_ENV: dev
  MONGO_URL: ${MONGO_URL:-mongodb://lucid:lucid@lucid_mongo:27017/lucid?authSource=admin&retryWrites=false}
  ONION: ${ONION:-}
  BLOCK_ONION: ${BLOCK_ONION:-}
  TOR_CONTROL_PASSWORD: ${TOR_CONTROL_PASSWORD:-}

networks:
  lucid_net:
    name: lucid-dev_lucid_net
    driver: bridge
    attachable: true

volumes:
  tor_data:
    name: lucid-dev_onion_state
    external: true
  mongo_data: {}
  onion_state: {}
  docker_data:
    name: lucid-dev_docker_data
    driver: local

services:
  devcontainer:
    container_name: lucid_devcontainer
    hostname: lucid-dev
    build:
      context: ../..
      dockerfile: .devcontainer/Dockerfile
      target: final
      args:
        - BUILDKIT_INLINE_CACHE=1
        - BUILDKIT_PROGRESS=plain
      # platforms:
        # - linux/arm64  # Target Pi 5 - Commented for local dev
    image: pickme/lucid:dev-dind
    privileged: true  # Required for Docker-in-Docker
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DOCKER_DEFAULT_PLATFORM=linux/amd64  # Changed from arm64 for local dev
      - LUCID_ENV=dev
      - PYTHONPATH=/workspaces/Lucid
      - MONGO_URL=mongodb://lucid:lucid@lucid_mongo:27017/lucid?authSource=admin&retryWrites=false
      - SERVICE_NAME=lucid-api
      - VERSION=0.1.0
      - PORT=8081
      - MONGO_INITDB_ROOT_USERNAME=lucid
      - MONGO_INITDB_ROOT_PASSWORD=lucid
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_BUILDKIT=1
    volumes:
      - type: bind
        source: ../..
        target: /workspaces/Lucid
        read_only: false
      # SSH support (Windows path compatibility)
      - type: bind
        source: ${HOME}/.ssh
        target: /root/.ssh
        read_only: true
      # Git configuration (Windows path compatibility)
      - type: bind
        source: ${HOME}/.gitconfig
        target: /root/.gitconfig
        read_only: true
      # Docker socket for Docker-in-Docker (read-write for container creation)
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: false
      # Docker data directory for DinD
      - type: volume
        source: docker_data
        target: /var/lib/docker
      # Onion state
      - onion_state:/run/lucid/onion:ro
      # Temp directory for builds
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 1G
    ports:
      - "8080:8080"  # API Gateway
      - "8081:8081"  # API Server
      - "8082:8082"  # Blockchain Core
      - "9050:9050"  # Tor SOCKS proxy
      - "9051:9051"  # Tor control port
      - "2222:22"    # SSH access
    networks:
      - lucid_net
    depends_on:
      lucid_mongo:
        condition: service_healthy
    command: ["/usr/local/bin/start-lucid-dev", "tail", "-f", "/dev/null"]
    profiles: [dev]
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    working_dir: /workspaces/Lucid
    
  tor-proxy:
    profiles: [dev]
    container_name: lucid_tor
    build:
      context: ../../02-network-security/tor
      dockerfile: Dockerfile
    env_file: [./.env]
    environment:
      <<: *default-env
    expose: ["9050", "9051"]
    volumes:
      - tor_data:/var/lib/tor
      - onion_state:/run/lucid/onion
      - ../../02-network-security/tor/torrc:/etc/tor/torrc:ro
      - ../../02-network-security/tor/tor-health.sh:/usr/local/bin/tor-health:ro
      - ../../02-network-security/tor/tor-show-onion.sh:/usr/local/bin/tor-show-onion:ro
      - ../../02-network-security/tor/scripts/create_ephemeral_onion.sh:/usr/local/bin/create-ephemeral-onion:ro
    networks:
      lucid_net:
        aliases: [lucid_net, tor-proxy, tor]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh /usr/local/bin/tor-health"]
      interval: 10s
      timeout: 6s
      retries: 18
      start_period: 25s
    security_opt:
      - no-new-privileges:true

  lucid_mongo:
    profiles: [dev]
    container_name: lucid_mongo
    image: mongo:7
    command: ["mongod", "--auth", "--bind_ip_all"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: lucid
      MONGO_INITDB_ROOT_PASSWORD: lucid
      MONGO_INITDB_DATABASE: lucid
    volumes:
      - mongo_data:/data/db
    networks: [lucid_net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval \"db.runCommand({ ping: 1 }).ok\" | grep -q 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    security_opt:
      - no-new-privileges:true

  lucid_api:
    profiles: [dev]
    build:
      context: ../../03-api-gateway/api
      dockerfile: Dockerfile.api
    container_name: lucid_api
    environment:
      <<: *default-env
      PYTHONPATH: /app
    volumes:
      - type: bind
        source: ../../03-api-gateway/api/app
        target: /app
      - onion_state:/run/lucid/onion:ro
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0
      --port 8081
      --proxy-headers
      --reload
    ports:
      - "8081:8081"
    networks: [lucid_net]
    depends_on:
      lucid_mongo:
        condition: service_healthy
      tor-proxy:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8081/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    working_dir: /app

  api-gateway:
    profiles: [dev]
    build:
      context: ../../03-api-gateway/gateway
      dockerfile: Dockerfile.gateway
    container_name: lucid_api_gateway
    environment:
      <<: *default-env
      API_UPSTREAM: "lucid_api:8081"
      GATEWAY_PORT: "8080"
    volumes:
      - onion_state:/run/lucid/onion:ro
    depends_on:
      lucid_api:
        condition: service_started
    ports:
      - "8080:8080"
    networks: [lucid_net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    security_opt:
      - no-new-privileges:true

  tunnel-tools:
    profiles: [dev]
    container_name: lucid_tunnel_tools
    build:
      context: ../../02-network-security/tunnels
      dockerfile: Dockerfile
    env_file: [./.env]
    environment:
      <<: *default-env
    depends_on:
      tor-proxy:
        condition: service_healthy
      lucid_api:
        condition: service_started
    expose: ["7000"]
    networks: [lucid_net]
    volumes:
      - onion_state:/run/lucid/onion
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  server-tools:
    profiles: [dev]
    container_name: lucid_server_tools
    image: alpine:3.22.1
    env_file: [./.env]
    environment:
      <<: *default-env
    networks: [lucid_net]
    depends_on:
      tor-proxy:
        condition: service_healthy
      lucid_mongo:
        condition: service_healthy
      lucid_api:
        condition: service_started
    command:
      - /bin/sh
      - -lc
      - |
        set -e
        apk add --no-cache bash curl jq bind-tools netcat-openbsd socat openssl || true
        echo "[server-tools] Ready. Utilities installed (or already present)."
        exec tail -f /dev/null
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
