# Path: 06-orchestration-runtime/compose/lucid-dev.yaml
# Lucid RDP — Development Docker Compose Stack

services:
  # --- API Gateway ---
  api-gateway:
    build:
      context: ../../03-api-gateway/gateway
      dockerfile: Dockerfile
    container_name: lucid_api_gateway
    ports:
      - "8080:8080"
    volumes:
      - ../../03-api-gateway/gateway:/app
    depends_on:
      - lucid_api
      - mongodb
    environment:
      - BLOCK_ONION=${BLOCK_ONION:-}
      - BLOCK_RPC_URL=${BLOCK_RPC_URL:-}
    networks:
      - lucid_net
    profiles: ["dev"]

  # --- Core Lucid API (FastAPI service) ---
  lucid_api:
    build:
      context: ../../03-api-gateway/api
      dockerfile: Dockerfile
    container_name: lucid_api
    ports:
      - "4000:4000"
    volumes:
      - ../../03-api-gateway/api:/app
    environment:
      - MONGO_URL=mongodb://mongodb:27017/lucid
    depends_on:
      - mongodb
    networks:
      - lucid_net
    profiles: ["dev"]

  # --- MongoDB (Development DB) ---
  mongodb:
    image: mongo:6.0
    container_name: lucid_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lucid_net
    profiles: ["dev"]

  # --- Tor Proxy ---
  tor-proxy:
    build:
      context: ../../02-network-security/tor
      dockerfile: Dockerfile
    container_name: lucid_tor
    ports:
      - "9050:9050"   # SOCKS proxy
      - "9051:9051"   # Control port
    volumes:
      - tor_data:/var/lib/tor
      - ../../02-network-security/tor/torrc:/etc/tor/torrc:ro
    networks:
      - lucid_net
    profiles: ["dev"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "grep -q 'Bootstrapped 100%' /var/lib/tor/notice.log || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- Reverse Tunnel Verification ---
  tunnel-check:
    build:
      context: ../../02-network-security/tunnels
      dockerfile: Dockerfile
    container_name: lucid_tunnel_check
    depends_on:
      - tor-proxy
    volumes:
      - tor_data:/var/lib/tor   # share Tor state for reading onion hostname
    networks:
      - lucid_net
    profiles: ["dev"]

volumes:
  mongo_data:
  tor_data:

networks:
  lucid_net:
    driver: bridge
