version: "3.9"

services:
  tor-proxy:
    build:
      context: ./06-orchestration-runtime/tor
      dockerfile: Dockerfile
    container_name: compose-tor-proxy-1
    restart: unless-stopped
    expose:
      - "9050"   # only inside Docker network
    volumes:
      - compose_tor_data:/var/lib/tor
    networks:
      - internal-net
      - secure-net
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]

  lucid_api:
    build:
      context: ./06-orchestration-runtime/lucid_api
      dockerfile: Dockerfile
    container_name: compose-lucid-api-1
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - tor-proxy
    networks:
      - internal-net

  api-gateway:
    build:
      context: ./06-orchestration-runtime/api-gateway
      dockerfile: Dockerfile
    container_name: compose-api-gateway-1
    restart: unless-stopped
    expose:
      - "4000"
    depends_on:
      - lucid_api
      - tor-proxy
    networks:
      - internal-net

  lucid_db:
    image: mongo:6.0
    container_name: compose-lucid-db-1
    restart: unless-stopped
    volumes:
      - compose_gateway_data:/data/db
    expose:
      - "27017"
    networks:
      - internal-net

volumes:
  compose_gateway_data:
  compose_tor_data:

networks:
  internal-net:
  secure-net:
