apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucid-api-gateway
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: lucid-blockchain
    lucid.service: api-gateway
    lucid.type: core
    lucid.platform: arm64
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/component: gateway
        app.kubernetes.io/part-of: lucid-blockchain
        lucid.service: api-gateway
        lucid.type: core
        lucid.platform: arm64
    spec:
      hostname: lucid-api-gateway
      containers:
      - name: api-gateway
        image: pickme/lucid-api-gateway:latest-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: https
        env:
        - name: LUCID_ENV
          value: "production"
        - name: LUCID_PLATFORM
          value: "arm64"
        - name: PROJECT_ROOT
          value: "/mnt/myssd/Lucid/Lucid"
        - name: SERVICE_NAME
          value: "api-gateway"
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8081"
        - name: API_GATEWAY_URL
          value: "http://lucid-api-gateway:8080"
        - name: API_GATEWAY_HOST
          value: "172.20.0.10"
        - name: MONGODB_URI
          value: "mongodb://lucid:$(MONGODB_PASSWORD)@mongodb-service:27017/lucid?authSource=admin"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MONGODB_PASSWORD
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: REDIS_PASSWORD
        - name: AUTH_SERVICE_URL
          value: "http://lucid-auth-service:8089"
        - name: BLOCKCHAIN_CORE_URL
          value: "http://lucid-blockchain-engine:8084"
        - name: SESSION_MANAGEMENT_URL
          value: "http://lucid-session-api:8087"
        - name: NODE_MANAGEMENT_URL
          value: "http://lucid-node-management:8095"
        - name: TRON_PAYMENT_URL
          value: "http://lucid-payment-gateway:8097"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_ALGORITHM
        volumeMounts:
        - name: api-gateway-config
          mountPath: /app/config
        - name: ssl-certs
          mountPath: /certs
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: api-gateway-config
        configMap:
          name: api-gateway-config
      - name: ssl-certs
        secret:
          secretName: ssl-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: lucid-api-gateway
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: lucid-blockchain
    lucid.service: api-gateway
    lucid.type: core
    lucid.platform: arm64
  annotations:
    service.beta.kubernetes.io/load-balancer-source-ranges: "172.20.0.0/16"
spec:
  selector:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8081
    targetPort: 8081
    name: https
  type: LoadBalancer
  loadBalancerIP: 172.20.0.10
  