apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mesh-controller
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: service-mesh-controller
    app.kubernetes.io/component: service-mesh
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: service-mesh-controller
      app.kubernetes.io/component: service-mesh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-mesh-controller
        app.kubernetes.io/component: service-mesh
        app.kubernetes.io/part-of: lucid-blockchain
    spec:
      containers:
      - name: service-mesh-controller
        image: pickme/lucid-service-mesh-controller:latest-arm64
        ports:
        - containerPort: 8500
          name: consul
        - containerPort: 8501
          name: consul-https
        env:
        - name: SERVICE_NAME
          value: "service-mesh-controller"
        - name: CONSUL_DATACENTER
          value: "lucid-dc"
        - name: CONSUL_BIND_INTERFACE
          value: "eth0"
        - name: CONSUL_CLIENT_INTERFACE
          value: "eth0"
        - name: CONSUL_RETRY_JOIN
          value: "consul-service"
        volumeMounts:
        - name: consul-config
          mountPath: /consul/config
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: consul-config
        configMap:
          name: consul-config
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: service-mesh-controller
    app.kubernetes.io/component: service-mesh
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  selector:
    app.kubernetes.io/name: service-mesh-controller
    app.kubernetes.io/component: service-mesh
  ports:
  - port: 8500
    targetPort: 8500
    name: consul
  - port: 8501
    targetPort: 8501
    name: consul-https
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: service-mesh-controller
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  consul.json: |
    {
      "datacenter": "lucid-dc",
      "data_dir": "/consul/data",
      "log_level": "INFO",
      "node_name": "consul-server",
      "server": true,
      "bootstrap_expect": 1,
      "ui_config": {
        "enabled": true
      },
      "connect": {
        "enabled": true
      },
      "ports": {
        "grpc": 8502
      }
    }
