# LUCID Payment Systems - TRON Payment Service - Phase 4
# Step 33: Phase 4 Container Builds
# Docker Compose configuration for TRON payment operations
# Deploy to isolated network (lucid-network-isolated) as support service cluster
# Distroless containers: 6 TRON payment services

version: '3.8'

services:
  # TRON Client Service - Phase 4
  tron-client:
    build:
      context: .
      dockerfile: Dockerfile.tron-client
    image: pickme/lucid-tron-client:latest-arm64
    platform: linux/arm64
    container_name: lucid-tron-client
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.support
      - ../../configs/environment/.env.tron-staking
    ports:
      - "8091:8091"
    environment:
      - TRON_NETWORK=shasta
      - TRON_HTTP_ENDPOINT=https://api.shasta.trongrid.io
      - TRONGRID_API_KEY=${TRONGRID_API_KEY}
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - SERVICE_NAME=tron-client
      - SERVICE_PORT=8091
    volumes:
      - tron_data:/data
      - tron_logs:/app/logs
    networks:
      - lucid-tron-isolated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8091/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=tron-client"
      - "lucid.cluster=tron-payment"
      - "lucid.phase=phase4"
      - "lucid.plane=wallet"
      - "lucid.isolation=payment-only"

  # TRON Payout Router Service - Phase 4
  payout-router:
    build:
      context: .
      dockerfile: Dockerfile.payout-router
    image: pickme/lucid-tron-payout-router:latest-arm64
    platform: linux/arm64
    container_name: lucid-payout-router
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.support
      - ../../configs/environment/.env.tron-staking
    ports:
      - "8092:8092"
    environment:
      - TRON_NETWORK=shasta
      - TRON_HTTP_ENDPOINT=https://api.shasta.trongrid.io
      - TRONGRID_API_KEY=${TRONGRID_API_KEY}
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - SERVICE_NAME=payout-router
      - SERVICE_PORT=8092
    volumes:
      - tron_data:/data
      - tron_logs:/app/logs
    networks:
      - lucid-tron-isolated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8092/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=payout-router"
      - "lucid.cluster=tron-payment"
      - "lucid.phase=phase4"
      - "lucid.plane=wallet"
      - "lucid.isolation=payment-only"

  # TRON Wallet Manager Service - Phase 4
  wallet-manager:
    build:
      context: .
      dockerfile: Dockerfile.wallet-manager
    image: pickme/lucid-tron-wallet-manager:latest-arm64
    platform: linux/arm64
    container_name: lucid-wallet-manager
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.support
      - ../../configs/environment/.env.tron-staking
    ports:
      - "8093:8093"
    environment:
      - TRON_NETWORK=shasta
      - TRON_HTTP_ENDPOINT=https://api.shasta.trongrid.io
      - TRONGRID_API_KEY=${TRONGRID_API_KEY}
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - SERVICE_NAME=wallet-manager
      - SERVICE_PORT=8093
    volumes:
      - tron_data:/data
      - tron_logs:/app/logs
    networks:
      - lucid-tron-isolated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8093/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=wallet-manager"
      - "lucid.cluster=tron-payment"
      - "lucid.phase=phase4"
      - "lucid.plane=wallet"
      - "lucid.isolation=payment-only"

  # TRON USDT Manager Service - Phase 4
  usdt-manager:
    build:
      context: .
      dockerfile: Dockerfile.usdt-manager
    image: pickme/lucid-tron-usdt-manager:latest-arm64
    platform: linux/arm64
    container_name: lucid-usdt-manager
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.support
      - ../../configs/environment/.env.tron-staking
    ports:
      - "8094:8094"
    environment:
      - TRON_NETWORK=shasta
      - TRON_HTTP_ENDPOINT=https://api.shasta.trongrid.io
      - TRONGRID_API_KEY=${TRONGRID_API_KEY}
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - SERVICE_NAME=usdt-manager
      - SERVICE_PORT=8094
    volumes:
      - tron_data:/data
      - tron_logs:/app/logs
    networks:
      - lucid-tron-isolated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8094/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=usdt-manager"
      - "lucid.cluster=tron-payment"
      - "lucid.phase=phase4"
      - "lucid.plane=wallet"
      - "lucid.isolation=payment-only"

  # TRON TRX Staking Service - Phase 4
  trx-staking:
    build:
      context: .
      dockerfile: Dockerfile.trx-staking
    image: pickme/lucid-tron-staking:latest-arm64
    platform: linux/arm64
    container_name: lucid-trx-staking
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.support
      - ../../configs/environment/.env.tron-staking
    ports:
      - "8095:8095"
    environment:
      - TRON_NETWORK=shasta
      - TRON_HTTP_ENDPOINT=https://api.shasta.trongrid.io
      - TRONGRID_API_KEY=${TRONGRID_API_KEY}
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - SERVICE_NAME=trx-staking
      - SERVICE_PORT=8095
    volumes:
      - tron_data:/data
      - tron_logs:/app/logs
    networks:
      - lucid-tron-isolated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8095/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=trx-staking"
      - "lucid.cluster=tron-payment"
      - "lucid.phase=phase4"
      - "lucid.plane=wallet"
      - "lucid.isolation=payment-only"

  # TRON Payment Gateway Service - Phase 4
  payment-gateway:
    build:
      context: .
      dockerfile: Dockerfile.payment-gateway
    image: pickme/lucid-tron-payment-gateway:latest-arm64
    platform: linux/arm64
    container_name: lucid-payment-gateway
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.support
      - ../../configs/environment/.env.tron-staking
    ports:
      - "8096:8096"
    environment:
      - TRON_NETWORK=shasta
      - TRON_HTTP_ENDPOINT=https://api.shasta.trongrid.io
      - TRONGRID_API_KEY=${TRONGRID_API_KEY}
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - SERVICE_NAME=payment-gateway
      - SERVICE_PORT=8096
    volumes:
      - tron_data:/data
      - tron_logs:/app/logs
    networks:
      - lucid-tron-isolated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8096/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=payment-gateway"
      - "lucid.cluster=tron-payment"
      - "lucid.phase=phase4"
      - "lucid.plane=wallet"
      - "lucid.isolation=payment-only"

  # Optional: TRON node for local development
  tron-node:
    image: tronprotocol/tron:latest
    container_name: lucid-tron-node
    env_file:
      - ../../configs/environment/.env.foundation
      - ../../configs/environment/.env.support
      - ../../configs/environment/.env.tron-staking
    ports:
      - "8097:8090"
      - "8098:8091"
    environment:
      - NET_TYPE=shasta
    volumes:
      - tron_node_data:/tron
    networks:
      - lucid-tron-isolated
    restart: unless-stopped
    profiles:
      - development

volumes:
  tron_data:
    driver: local
  tron_logs:
    driver: local
  tron_node_data:
    driver: local

networks:
  lucid-tron-isolated:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
    labels:
      - "lucid.network=tron-payment-isolated"
      - "lucid.phase=phase4"
      - "lucid.cluster=tron-payment"
      - "lucid.isolation=payment-only"