apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  SERVICE_NAME: "api-gateway"
  API_VERSION: "v1"
  DEBUG: "false"
  HTTP_PORT: "8080"
  HTTPS_PORT: "8081"
  AUTH_PORT: "8082"
  RATE_LIMITER_PORT: "8083"
  
  # Backend Service URLs
  BLOCKCHAIN_CORE_URL: "http://blockchain-core-service:8084"
  SESSION_MANAGEMENT_URL: "http://session-management-service:8085"
  AUTH_SERVICE_URL: "http://auth-service:8089"
  TRON_PAYMENT_URL: "http://tron-payment-service:8085"
  
  # Database Configuration
  MONGODB_URI: "mongodb://mongodb-service:27017/lucid_gateway"
  REDIS_URL: "redis://redis-service:6379/0"
  
  # Security Configuration
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # Rate Limiting Configuration
  RATE_LIMIT_REQUESTS_PER_MINUTE: "100"
  RATE_LIMIT_BURST_SIZE: "200"
  RATE_LIMIT_ENABLED: "true"
  
  # SSL Configuration
  SSL_ENABLED: "true"
  
  # CORS Configuration
  CORS_ORIGINS: "http://localhost:3000,https://lucid.onion"
  CORS_ALLOW_CREDENTIALS: "true"
  
  # Service Mesh Configuration
  SERVICE_MESH_ENABLED: "true"
  SERVICE_DISCOVERY_URL: "http://consul-service:8500"
