apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  SERVICE_NAME: "api-gateway"
  API_VERSION: "v1"
  DEBUG: "false"
  HTTP_PORT: "8080"
  HTTPS_PORT: "8081"
  
  # IP Address Configuration (per essentials.md)
  API_GATEWAY_HOST: "172.20.0.10"
  API_GATEWAY_GUI_HOST: "172.22.0.10"
  
  # Backend Service URLs (corrected service names)
  BLOCKCHAIN_CORE_URL: "http://lucid-blockchain-engine:8084"
  SESSION_MANAGEMENT_URL: "http://lucid-session-api:8087"
  AUTH_SERVICE_URL: "http://lucid-auth-service:8089"
  TRON_PAYMENT_URL: "http://lucid-payment-gateway:8097"
  NODE_MANAGEMENT_URL: "http://lucid-node-management:8095"
  ADMIN_INTERFACE_URL: "http://lucid-admin-interface:8083"
  
  # Database Configuration (with password placeholder)
  MONGODB_URI: "mongodb://lucid:{MONGODB_PASSWORD}@mongodb-service:27017/lucid_gateway?authSource=admin"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis-service:6379/0"
  
  # Security Configuration
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # Rate Limiting Configuration
  RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  RATE_LIMIT_BURST_SIZE: "200"
  RATE_LIMIT_ENABLED: "true"
  
  # SSL Configuration
  SSL_ENABLED: "true"
  
  # CORS Configuration
  CORS_ORIGINS: "http://localhost:3000,https://lucid.onion"
  CORS_ALLOW_CREDENTIALS: "true"
  
  # Service Mesh Configuration
  SERVICE_MESH_ENABLED: "true"
  SERVICE_DISCOVERY_URL: "http://consul-service:8500"
  
  # Network Configuration (per essentials.md)
  LUCID_PI_NETWORK: "lucid-pi-network"
  LUCID_PI_SUBNET: "172.20.0.0/16"
  LUCID_PI_GATEWAY: "172.20.0.1"
  LUCID_GUI_NETWORK: "lucid-gui-network"
  LUCID_GUI_SUBNET: "172.22.0.0/16"
  LUCID_GUI_GATEWAY: "172.22.0.1"
  PROJECT_ROOT: "/mnt/myssd/Lucid/Lucid"
  
  # Electron GUI Endpoint (per essentials.md)
  ELECTRON_GUI_ENDPOINT: "http://172.20.0.10:8080/api/v1"