apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  SERVICE_NAME: "auth-service"
  CONTAINER_NAME: "lucid-auth-service"
  DEBUG: "false"
  
  # Port Configuration (per essentials.md)
  AUTH_PORT: "8089"
  
  # IP Address Configuration (per essentials.md)
  AUTH_SERVICE_HOST: "172.20.0.14"
  AUTH_SERVICE_URL: "http://lucid-auth-service:8089"
  
  # Database Configuration (with password placeholder)
  MONGODB_URI: "mongodb://lucid:{MONGODB_PASSWORD}@mongodb-service:27017/lucid_auth?authSource=admin"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis-service:6379/6"
  
  # JWT Configuration
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # Authentication Methods
  MAGIC_LINK_ENABLED: "true"
  TOTP_ENABLED: "true"
  HARDWARE_WALLET_ENABLED: "true"
  
  # Hardware Wallet Configuration
  LEDGER_ENABLED: "true"
  TREZOR_ENABLED: "true"
  KEEPKEY_ENABLED: "true"
  
  # TRON Signature Verification
  TRON_SIGNATURE_VERIFICATION_ENABLED: "true"
  TRON_NETWORK: "mainnet"
  
  # RBAC Configuration
  RBAC_ENABLED: "true"
  ROLE_HIERARCHY_ENABLED: "true"
  PERMISSION_CACHING_ENABLED: "true"
  
  # Session Management
  SESSION_TIMEOUT: "3600"
  MAX_CONCURRENT_SESSIONS: "10"
  SESSION_CLEANUP_INTERVAL: "300"
  
  # Security Configuration
  PASSWORD_HASHING_ALGORITHM: "bcrypt"
  PASSWORD_MIN_LENGTH: "8"
  ACCOUNT_LOCKOUT_ENABLED: "true"
  MAX_LOGIN_ATTEMPTS: "5"
  
  # Health Check Configuration (per essentials.md)
  HEALTHCHECK_PORT: "8089"
  HEALTHCHECK_PATH: "/health"
  
  # Network Configuration (per essentials.md)
  LUCID_PI_NETWORK: "lucid-pi-network"
  LUCID_PI_SUBNET: "172.20.0.0/16"
  LUCID_PI_GATEWAY: "172.20.0.1"
  PROJECT_ROOT: "/mnt/myssd/Lucid/Lucid"
  LUCID_PLATFORM: "arm64"
  LUCID_ENV: "production"