apiVersion: v1
kind: ConfigMap
metadata:
  name: rdp-services-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-services
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  SERVICE_NAME: "rdp-services"
  DEBUG: "false"
  
  # Port Configuration (Corrected per essentials.md)
  SERVER_MANAGER_PORT: "8081"
  SERVER_MANAGER_API_PORT: "8090"
  XRDP_PORT: "3389"
  RDP_CONTROLLER_PORT: "8092"
  RDP_MONITOR_PORT: "8093"
  
  # IP Address Configuration (per essentials.md)
  RDP_SERVER_MANAGER_HOST: "172.20.0.21"
  RDP_XRDP_HOST: "172.20.0.22"
  RDP_CONTROLLER_HOST: "172.20.0.23"
  RDP_MONITOR_HOST: "172.20.0.24"
  
  # Service URLs (per essentials.md)
  RDP_SERVER_MANAGER_URL: "http://lucid-rdp-server-manager:8081"
  RDP_XRDP_URL: "http://lucid-rdp-xrdp:3389"
  RDP_CONTROLLER_URL: "http://lucid-rdp-controller:8092"
  RDP_MONITOR_URL: "http://lucid-rdp-monitor:8093"
  
  # Container Names (per essentials.md)
  RDP_SERVER_MANAGER_CONTAINER: "lucid-rdp-server-manager"
  RDP_XRDP_CONTAINER: "lucid-rdp-xrdp"
  RDP_CONTROLLER_CONTAINER: "lucid-rdp-controller"
  RDP_MONITOR_CONTAINER: "lucid-rdp-monitor"
  
  # RDP Configuration
  RDP_PORT_RANGE_START: "13389"
  RDP_PORT_RANGE_END: "14389"
  MAX_CONCURRENT_SESSIONS: "100"
  SESSION_TIMEOUT: "3600"
  
  # XRDP Configuration
  XRDP_CONFIG_PATH: "/etc/xrdp"
  XRDP_LOG_PATH: "/var/log/xrdp"
  XRDP_ENABLE_SSL: "true"
  
  # Resource Monitoring
  MONITORING_INTERVAL: "30"
  CPU_THRESHOLD: "80"
  MEMORY_THRESHOLD: "80"
  DISK_THRESHOLD: "90"
  
  # Database Configuration (with password placeholder)
  MONGODB_URI: "mongodb://lucid:{MONGODB_PASSWORD}@mongodb-service:27017/lucid_rdp?authSource=admin"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis-service:6379/2"
  
  # Session Management
  SESSION_CLEANUP_INTERVAL: "300"
  MAX_SESSION_DURATION: "7200"
  AUTO_CLEANUP_ENABLED: "true"
  
  # Health Check Ports (per essentials.md)
  SERVER_MANAGER_HEALTHCHECK_PORT: "8081"
  RDP_CONTROLLER_HEALTHCHECK_PORT: "8092"
  RDP_MONITOR_HEALTHCHECK_PORT: "8093"
  HEALTHCHECK_PATH: "/health"
  
  # Network Configuration (per essentials.md)
  LUCID_PI_NETWORK: "lucid-pi-network"
  LUCID_PI_SUBNET: "172.20.0.0/16"
  LUCID_PI_GATEWAY: "172.20.0.1"
  PROJECT_ROOT: "/mnt/myssd/Lucid/Lucid"
  LUCID_PLATFORM: "arm64"
  LUCID_ENV: "production"