apiVersion: v1
kind: ConfigMap
metadata:
  name: rdp-services-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-services
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  SERVICE_NAME: "rdp-services"
  DEBUG: "false"
  
  # Port Configuration
  SERVER_MANAGER_PORT: "8090"
  XRDP_PORT: "8091"
  SESSION_CONTROLLER_PORT: "8092"
  RESOURCE_MONITOR_PORT: "8093"
  
  # RDP Configuration
  RDP_PORT_RANGE_START: "13389"
  RDP_PORT_RANGE_END: "14389"
  MAX_CONCURRENT_SESSIONS: "100"
  SESSION_TIMEOUT: "3600"
  
  # XRDP Configuration
  XRDP_CONFIG_PATH: "/etc/xrdp"
  XRDP_LOG_PATH: "/var/log/xrdp"
  XRDP_ENABLE_SSL: "true"
  
  # Resource Monitoring
  MONITORING_INTERVAL: "30"
  CPU_THRESHOLD: "80"
  MEMORY_THRESHOLD: "80"
  DISK_THRESHOLD: "90"
  
  # Database Configuration
  MONGODB_URI: "mongodb://mongodb-service:27017/lucid_rdp"
  REDIS_URL: "redis://redis-service:6379/2"
  
  # Session Management
  SESSION_CLEANUP_INTERVAL: "300"
  MAX_SESSION_DURATION: "7200"
  AUTO_CLEANUP_ENABLED: "true"
