apiVersion: v1
kind: ConfigMap
metadata:
  name: session-management-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: session-management
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  SERVICE_NAME: "session-management"
  DEBUG: "false"
  
  # Port Configuration (Corrected per essentials.md)
  PIPELINE_PORT: "8087"
  RECORDER_PORT: "8090"
  PROCESSOR_PORT: "8091"
  STORAGE_PORT: "8082"
  API_PORT: "8087"
  
  # IP Address Configuration (per essentials.md)
  SESSION_PIPELINE_HOST: "172.20.0.20"
  SESSION_RECORDER_HOST: "172.20.0.20"
  CHUNK_PROCESSOR_HOST: "172.20.0.20"
  SESSION_STORAGE_HOST: "172.20.0.20"
  SESSION_API_HOST: "172.20.0.20"
  
  # Service URLs (per essentials.md)
  SESSION_PIPELINE_URL: "http://lucid-session-pipeline:8087"
  SESSION_RECORDER_URL: "http://lucid-session-recorder:8090"
  CHUNK_PROCESSOR_URL: "http://lucid-chunk-processor:8091"
  SESSION_STORAGE_URL: "http://lucid-session-storage:8082"
  SESSION_API_URL: "http://lucid-session-api:8087"
  
  # Database Configuration (with password placeholder)
  MONGODB_URI: "mongodb://lucid:{MONGODB_PASSWORD}@mongodb-service:27017/lucid_sessions?authSource=admin"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis-service:6379/1"
  
  # Pipeline Configuration
  CHUNK_SIZE_MB: "10"
  COMPRESSION_LEVEL: "6"
  ENCRYPTION_ALGORITHM: "AES-256-GCM"
  
  # Processing Configuration
  MAX_WORKERS: "10"
  BATCH_SIZE: "100"
  PROCESSING_TIMEOUT: "300"
  
  # Storage Configuration
  CHUNK_STORAGE_PATH: "/data/sessions"
  METADATA_STORAGE_PATH: "/data/metadata"
  BACKUP_STORAGE_PATH: "/data/backups"
  
  # Blockchain Integration (corrected service name)
  BLOCKCHAIN_ANCHORING_URL: "http://lucid-session-anchoring:8085"
  ANCHORING_ENABLED: "true"
  ANCHORING_BATCH_SIZE: "10"
  
  # Network Configuration (per essentials.md)
  LUCID_PI_NETWORK: "lucid-pi-network"
  LUCID_PI_SUBNET: "172.20.0.0/16"
  LUCID_PI_GATEWAY: "172.20.0.1"
  PROJECT_ROOT: "/mnt/myssd/Lucid/Lucid"
  
  # Electron GUI Endpoint (per essentials.md)
  ELECTRON_GUI_ENDPOINT: "http://172.20.0.20:8087/api/v1"