apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  serviceName: elasticsearch-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: lucid-blockchain
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.11.0
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: xpack.security.enabled
          value: "true"
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ELASTICSEARCH_PASSWORD
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: database
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9300
    targetPort: 9300
    name: transport
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  elasticsearch.yml: |
    cluster.name: lucid-cluster
    node.name: lucid-node
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    discovery.type: single-node
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.http.ssl.enabled: true
    xpack.security.authc.api_key.enabled: true
