apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lucid-mongodb
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: lucid-blockchain
    lucid.service: mongodb
    lucid.type: foundation
    lucid.platform: arm64
spec:
  serviceName: lucid-mongodb
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: lucid-blockchain
        lucid.service: mongodb
        lucid.type: foundation
        lucid.platform: arm64
    spec:
      hostname: lucid-mongodb
      containers:
      - name: mongodb
        image: pickme/lucid-mongodb:latest-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: LUCID_ENV
          value: "production"
        - name: LUCID_PLATFORM
          value: "arm64"
        - name: PROJECT_ROOT
          value: "/mnt/myssd/Lucid/Lucid"
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MONGODB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MONGODB_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: "lucid"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          exec:
            command:
            - mongosh
            - --quiet
            - -u
            - $(MONGO_INITDB_ROOT_USERNAME)
            - -p
            - $(MONGO_INITDB_ROOT_PASSWORD)
            - --authenticationDatabase
            - admin
            - --eval
            - "db.runCommand({ ping: 1 }).ok"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongosh
            - --quiet
            - -u
            - $(MONGO_INITDB_ROOT_USERNAME)
            - -p
            - $(MONGO_INITDB_ROOT_PASSWORD)
            - --authenticationDatabase
            - admin
            - --eval
            - "db.runCommand({ ping: 1 }).ok"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mongodb-config
        configMap:
          name: mongodb-config
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: lucid-mongodb
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: lucid-blockchain
    lucid.service: mongodb
    lucid.type: foundation
    lucid.platform: arm64
spec:
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  type: ClusterIP
  clusterIP: 172.20.0.11
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    net:
      port: 27017
      bindIp: 0.0.0.0
    security:
      authorization: enabled
    replication:
      replSetName: lucid-rs
      