# Blockchain Core Service Configuration
# Cluster: 02-BLOCKCHAIN-CORE
# Service: lucid_blocks Blockchain System
# Ports: 8084-8087
# CRITICAL: TRON ISOLATION - NO TRON dependencies

service:
  name: lucid-blocks
  version: "1.0.0"
  description: "Lucid Blockchain Core - lucid_blocks system"
  cluster_id: "02-blockchain-core-cluster"
  blockchain_network: "lucid_blocks"
  
# Port Configuration
ports:
  blockchain_engine: 8084
  session_anchoring: 8085
  block_manager: 8086
  data_chain: 8087

# Container Configuration
containers:
  blockchain_engine:
    name: lucid-blockchain-engine
    base_image: "pickme/lucid-blockchain-engine:latest-arm64"  # ✅ CORRECT
    tag: "latest"
    multi_stage_build: true
  session_anchoring:
    name: lucid-session-anchoring
    base_image: "pickme/lucid-session-anchoring:latest-arm64"  # ✅ CORRECT
    tag: "latest"
    multi_stage_build: true
  block_manager:
    name: lucid-block-manager
    base_image: "pickme/lucid-block-manager:latest-arm64"  # ✅ CORRECT
    tag: "latest"
    multi_stage_build: true
  data_chain:
    name: lucid-data-chain
    base_image: "pickme/lucid-data-chain:latest-arm64"  # ✅ CORRECT
    tag: "latest"
    multi_stage_build: true

# Service Dependencies
dependencies:
  internal:
    - name: "api-gateway"
      url: "http://api-gateway:8080"
      required: true
    - name: "session-management"
      url: "http://session-management:8085"
      required: true
  external:
    - name: "mongodb"
      url: "mongodb://mongodb:27017/lucid_blocks"
      required: true
  storage:
    - name: "file_system"
      path: "/data"
      required: true
      volumes:
        - "blockchain_data:/data/blocks"
        - "merkle_data:/data/merkle"
        - "chunk_data:/data/chunks"

# Blockchain Configuration
blockchain:
  consensus_algorithm: "PoOT"  # Proof of Observation Time
  block_time_seconds: 10
  block_size_limit_mb: 1
  max_transactions_per_block: 1000
  genesis_block:
    height: 0
    timestamp: "2025-01-01T00:00:00Z"
    previous_hash: "0"
    merkle_root: "0"
  
# Consensus Configuration
consensus:
  algorithm: "PoOT"
  timeout: 30
  participants_min: 3
  validation_required: true
  voting_threshold: 0.67
  round_timeout: 60
  max_rounds: 10
  
# Session Anchoring Configuration
session_anchoring:
  batch_size: 10
  timeout: 60
  merkle_tree_height_max: 20
  validation_required: true
  proof_generation: true
  integrity_verification: true
  
# Block Management Configuration
block_management:
  storage_path: "/data/blocks"
  max_blocks_in_memory: 1000
  block_validation: true
  chain_continuity_check: true
  orphan_block_handling: true
  block_compression: true
  
# Data Chain Configuration
data_chain:
  chunk_storage_path: "/data/chunks"
  merkle_storage_path: "/data/merkle"
  max_chunk_size: "10MB"
  compression_enabled: true
  encryption_enabled: true
  integrity_checks: true
  
# Merkle Tree Configuration
merkle_tree:
  algorithm: "sha256"
  max_height: 20
  proof_generation: true
  validation_required: true
  storage_optimization: true
  batch_processing: true

# Network Configuration
network:
  peer_discovery: true
  sync_interval: 30
  tor_network_required: true
  max_peers: 50
  connection_timeout: 30
  keep_alive: true
  
# Security Configuration
security:
  block_signature_required: true
  transaction_signature_required: true
  merkle_proof_validation: true
  cryptographic_validation: true
  network_security: true
  access_control:
    node_authentication: true
    consensus_participation: true
    api_access: true
    data_access: true

# Database Configuration
database:
  mongodb:
    uri: "mongodb://mongodb:27017/lucid_blocks"
    database: "lucid_blocks"
    collections:
      - "blocks"
      - "transactions"
      - "consensus_rounds"
      - "merkle_trees"
      - "anchoring_records"
    indexes:
      - "block_height"
      - "transaction_hash"
      - "session_id"
      - "merkle_root"
    connection_pool: 10
    timeout: 30

# API Configuration
api:
  version: "v1"
  base_path: "/api/v1"
  endpoints:
    blockchain:
      - "GET /chain/info"
      - "GET /chain/status"
      - "GET /chain/height"
      - "GET /chain/network"
    blocks:
      - "GET /blocks"
      - "GET /blocks/{block_id}"
      - "GET /blocks/height/{height}"
      - "GET /blocks/latest"
      - "POST /blocks/validate"
    transactions:
      - "POST /transactions"
      - "GET /transactions/{tx_id}"
      - "GET /transactions/pending"
      - "POST /transactions/batch"
    anchoring:
      - "POST /anchoring/session"
      - "GET /anchoring/session/{session_id}"
      - "POST /anchoring/verify"
      - "GET /anchoring/status"
    consensus:
      - "GET /consensus/status"
      - "GET /consensus/participants"
      - "POST /consensus/vote"
      - "GET /consensus/history"
    merkle:
      - "POST /merkle/build"
      - "GET /merkle/{root_hash}"
      - "POST /merkle/verify"
      - "GET /merkle/validation/{session_id}"

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  structured: true
  blockchain_events: true
  consensus_events: true
  transaction_events: true
  error_events: true
  correlation_id: true

# Health Check Configuration
health_check:
  blockchain_engine:
    endpoint: "/api/v1/chain/status"
    interval: 30
    timeout: 10
    retries: 3
  session_anchoring:
    endpoint: "/api/v1/anchoring/status"
    interval: 30
    timeout: 10
    retries: 3
  block_manager:
    endpoint: "/api/v1/blocks/latest"
    interval: 30
    timeout: 10
    retries: 3
  data_chain:
    endpoint: "/api/v1/chain/info"
    interval: 30
    timeout: 10
    retries: 3

# Metrics Configuration
metrics:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
  custom_metrics:
    - "block_creation_rate"
    - "transaction_throughput"
    - "consensus_participation"
    - "merkle_tree_generation_time"
    - "session_anchoring_success_rate"
    - "block_validation_time"
    - "network_sync_status"

# Performance Configuration
performance:
  max_connections: 1000
  connection_timeout: 30
  request_timeout: 60
  keep_alive: true
  keep_alive_timeout: 65
  max_request_size: "10MB"
  max_response_size: "100MB"
  compression_enabled: true
  caching_enabled: true

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"
  grafana:
    enabled: true
    dashboard_id: "blockchain-core"
  alerts:
    - name: "consensus_failure"
      condition: "consensus_success_rate < 0.8"
      severity: "critical"
    - name: "block_creation_delay"
      condition: "block_creation_time > 15"
      severity: "warning"
    - name: "session_anchoring_failure"
      condition: "anchoring_success_rate < 0.9"
      severity: "warning"
    - name: "network_sync_issues"
      condition: "network_sync_status == 0"
      severity: "critical"

# Deployment Configuration
deployment:
  replicas: 2
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
  strategy:
    type: "RollingUpdate"
    rolling_update:
      max_unavailable: 1
      max_surge: 1
  volumes:
    - name: "blockchain_data"
      path: "/data/blocks"
      size: "100Gi"
    - name: "merkle_data"
      path: "/data/merkle"
      size: "50Gi"
    - name: "chunk_data"
      path: "/data/chunks"
      size: "500Gi"

# TRON Isolation Compliance
tron_isolation:
  enabled: true
  strict_mode: true
  validation:
    - "NO TRON dependencies"
    - "NO payment processing"
    - "NO TRON network access"
    - "NO USDT operations"
    - "NO TRX staking"
    - "NO TRON contract interactions"
  allowed_operations:
    - "lucid_blocks blockchain"
    - "session anchoring"
    - "consensus (PoOT)"
    - "block management"
    - "data chain operations"
    - "Merkle tree validation"
  forbidden_operations:
    - "TRON network operations"
    - "USDT-TRC20 transactions"
    - "TRON wallet operations"
    - "TRON payout processing"
    - "TRX staking operations"
    - "TRON contract interactions"

# Environment-specific Overrides
environments:
  development:
    debug: true
    log_level: "DEBUG"
    consensus:
      participants_min: 1
    blockchain:
      block_time_seconds: 5
      
  staging:
    debug: false
    log_level: "INFO"
    consensus:
      participants_min: 2
    blockchain:
      block_time_seconds: 10
      
  production:
    debug: false
    log_level: "WARN"
    consensus:
      participants_min: 3
    blockchain:
      block_time_seconds: 10
    security:
      enhanced: true
    tron_isolation:
      strict_mode: true

# Validation Rules
validation:
  required_fields:
    - "service.name"
    - "service.version"
    - "blockchain.consensus_algorithm"
    - "ports.blockchain_engine"
    - "containers.blockchain_engine.base_image"
  port_ranges:
    blockchain_engine: [8000, 8999]
    session_anchoring: [8000, 8999]
    block_manager: [8000, 8999]
    data_chain: [8000, 8999]
  resource_limits:
    cpu_max: "8"
    memory_max: "16Gi"
  security_requirements:
    - "tron_isolation.enabled"
    - "security.block_signature_required"
    - "security.transaction_signature_required"
    - "network.tor_network_required"
