apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-management
  namespace: lucid-system
spec:
  template:
    spec:
      containers:
      - name: session-management
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532  # distroless nonroot user
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532  # distroless nonroot group
          fsGroup: 65532
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        imagePullPolicy: Always
        env:
        - name: LUCID_PI_NETWORK
          value: "lucid-pi-network"
        - name: LUCID_PI_SUBNET
          value: "172.20.0.0/16"
        - name: LUCID_PI_GATEWAY
          value: "172.20.0.1"
