apiVersion: apps/v1
kind: Deployment
metadata:
  name: tron-payment
  namespace: lucid-system
spec:
  template:
    spec:
      containers:
      - name: tron-payment
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532  # distroless nonroot user
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532  # distroless nonroot group
          fsGroup: 65532
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        imagePullPolicy: Always
        env:
        - name: LUCID_TRON_ISOLATED
          value: "lucid-tron-isolated"
        - name: LUCID_TRON_SUBNET
          value: "172.21.0.0/16"
        - name: LUCID_TRON_GATEWAY
          value: "172.21.0.1"
        - name: TRON_ISOLATION_ENABLED
          value: "true"
