# Lucid Electron-GUI Distroless Services
# Docker Compose Configuration for Raspberry Pi (linux/arm64)
# Network: lucid-pi-network (172.20.0.0/16)
# Date: 2025-01-24

version: '3.8'

services:
  # Admin Electron-GUI Service
  lucid-electron-gui-admin:
    build:
      context: .
      dockerfile: distroless/Dockerfile.admin
    image: pickme/lucid-electron-gui-admin:latest-arm64
    container_name: lucid-electron-gui-admin
    networks:
      - lucid-pi-network
    ipv4_address: 172.20.0.100
    hostname: lucid-electron-gui-admin
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ELECTRON_GUI_PROFILE=admin
      - ELECTRON_GUI_NETWORK=lucid-pi-network
      - ELECTRON_GUI_API_BASE_URL=http://172.20.0.10:8080/api/v1
      - ELECTRON_GUI_CONFIG_FILE=/app/configs/api-services.conf
      - ELECTRON_GUI_HOST=172.20.0.100
      - ELECTRON_GUI_PORT=3000
    volumes:
      - electron-gui-admin-data:/app/data
      - electron-gui-admin-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=electron-gui-admin"
      - "lucid.profile=admin"
      - "lucid.network=lucid-pi-network"
      - "lucid.access=full"

  # User Electron-GUI Service
  lucid-electron-gui-user:
    build:
      context: .
      dockerfile: distroless/Dockerfile.user
    image: pickme/lucid-electron-gui-user:latest-arm64
    container_name: lucid-electron-gui-user
    networks:
      - lucid-pi-network
    ipv4_address: 172.20.0.101
    hostname: lucid-electron-gui-user
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - ELECTRON_GUI_PROFILE=user
      - ELECTRON_GUI_NETWORK=lucid-pi-network
      - ELECTRON_GUI_API_BASE_URL=http://172.20.0.10:8080/api/v1
      - ELECTRON_GUI_CONFIG_FILE=/app/configs/api-services-user.conf
      - ELECTRON_GUI_HOST=172.20.0.101
      - ELECTRON_GUI_PORT=3001
    volumes:
      - electron-gui-user-data:/app/data
      - electron-gui-user-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=electron-gui-user"
      - "lucid.profile=user"
      - "lucid.network=lucid-pi-network"
      - "lucid.access=restricted"

  # Node Operator Electron-GUI Service
  lucid-electron-gui-node:
    build:
      context: .
      dockerfile: distroless/Dockerfile.node
    image: pickme/lucid-electron-gui-node:latest-arm64
    container_name: lucid-electron-gui-node
    networks:
      - lucid-pi-network
    ipv4_address: 172.20.0.102
    hostname: lucid-electron-gui-node
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - ELECTRON_GUI_PROFILE=node_operator
      - ELECTRON_GUI_NETWORK=lucid-pi-network
      - ELECTRON_GUI_API_BASE_URL=http://172.20.0.10:8080/api/v1
      - ELECTRON_GUI_CONFIG_FILE=/app/configs/api-services-node.conf
      - ELECTRON_GUI_HOST=172.20.0.102
      - ELECTRON_GUI_PORT=3002
    volumes:
      - electron-gui-node-data:/app/data
      - electron-gui-node-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "lucid.service=electron-gui-node"
      - "lucid.profile=node_operator"
      - "lucid.network=lucid-pi-network"
      - "lucid.access=restricted"

networks:
  lucid-pi-network:
    external: true
    name: lucid-pi-network

volumes:
  electron-gui-admin-data:
    driver: local
    labels:
      - "lucid.service=electron-gui-admin"
      - "lucid.type=data"
  electron-gui-admin-logs:
    driver: local
    labels:
      - "lucid.service=electron-gui-admin"
      - "lucid.type=logs"
  electron-gui-user-data:
    driver: local
    labels:
      - "lucid.service=electron-gui-user"
      - "lucid.type=data"
  electron-gui-user-logs:
    driver: local
    labels:
      - "lucid.service=electron-gui-user"
      - "lucid.type=logs"
  electron-gui-node-data:
    driver: local
    labels:
      - "lucid.service=electron-gui-node"
      - "lucid.type=data"
  electron-gui-node-logs:
    driver: local
    labels:
      - "lucid.service=electron-gui-node"
      - "lucid.type=logs"
