apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-management
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: node-management
    app.kubernetes.io/component: node
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: node-management
      app.kubernetes.io/component: node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-management
        app.kubernetes.io/component: node
        app.kubernetes.io/part-of: lucid-blockchain
    spec:
      containers:
      - name: node-management
        image: lucid-node-management:latest
        ports:
        - containerPort: 8095
          name: http
        env:
        - name: SERVICE_NAME
          value: "node-management"
        - name: NODE_API_PORT
          value: "8095"
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/lucid_nodes"
        - name: REDIS_URL
          value: "redis://redis-service:6379/3"
        - name: TRON_PAYMENT_URL
          value: "http://tron-payment-service:8085"
        - name: NODE_REGISTRATION_ENABLED
          value: "true"
        - name: NODE_VERIFICATION_REQUIRED
          value: "true"
        - name: MAX_NODES_PER_POOL
          value: "100"
        - name: NODE_HEALTH_CHECK_INTERVAL
          value: "60"
        - name: POOT_CALCULATION_INTERVAL
          value: "300"
        - name: POOT_SCORE_THRESHOLD
          value: "0.5"
        - name: POOT_VALIDATION_REQUIRED
          value: "true"
        - name: POOL_CREATION_ENABLED
          value: "true"
        - name: MAX_POOLS
          value: "10"
        - name: POOL_BALANCE_THRESHOLD
          value: "1000"
        - name: RESOURCE_MONITORING_ENABLED
          value: "true"
        - name: CPU_MONITORING_INTERVAL
          value: "30"
        - name: MEMORY_MONITORING_INTERVAL
          value: "30"
        - name: DISK_MONITORING_INTERVAL
          value: "60"
        - name: PAYOUT_PROCESSING_ENABLED
          value: "true"
        - name: PAYOUT_BATCH_SIZE
          value: "50"
        - name: PAYOUT_INTERVAL
          value: "3600"
        volumeMounts:
        - name: node-config
          mountPath: /app/config
        - name: node-data
          mountPath: /data/nodes
        resources:
          requests:
            cpu: "300m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8095
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8095
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: node-config
        configMap:
          name: node-management-config
      - name: node-data
        persistentVolumeClaim:
          claimName: node-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node-management-service
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: node-management
    app.kubernetes.io/component: node
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  selector:
    app.kubernetes.io/name: node-management
    app.kubernetes.io/component: node
  ports:
  - port: 8095
    targetPort: 8095
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-data-pvc
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: node-management
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
