apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdp-services
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-services
    app.kubernetes.io/component: rdp
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rdp-services
      app.kubernetes.io/component: rdp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rdp-services
        app.kubernetes.io/component: rdp
        app.kubernetes.io/part-of: lucid-blockchain
    spec:
      containers:
      - name: rdp-services
        image: lucid-rdp-services:latest
        ports:
        - containerPort: 8090
          name: server-manager
        - containerPort: 8091
          name: xrdp
        - containerPort: 8092
          name: session-controller
        - containerPort: 8093
          name: resource-monitor
        env:
        - name: SERVICE_NAME
          value: "rdp-services"
        - name: SERVER_MANAGER_PORT
          value: "8090"
        - name: XRDP_PORT
          value: "8091"
        - name: SESSION_CONTROLLER_PORT
          value: "8092"
        - name: RESOURCE_MONITOR_PORT
          value: "8093"
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/lucid_rdp"
        - name: REDIS_URL
          value: "redis://redis-service:6379/2"
        - name: RDP_PORT_RANGE_START
          value: "13389"
        - name: RDP_PORT_RANGE_END
          value: "14389"
        - name: MAX_CONCURRENT_SESSIONS
          value: "100"
        - name: SESSION_TIMEOUT
          value: "3600"
        volumeMounts:
        - name: rdp-config
          mountPath: /app/config
        - name: rdp-data
          mountPath: /data/rdp
        - name: xrdp-config
          mountPath: /etc/xrdp
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: rdp-config
        configMap:
          name: rdp-services-config
      - name: rdp-data
        persistentVolumeClaim:
          claimName: rdp-data-pvc
      - name: xrdp-config
        configMap:
          name: xrdp-config
---
apiVersion: v1
kind: Service
metadata:
  name: rdp-services-service
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-services
    app.kubernetes.io/component: rdp
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  selector:
    app.kubernetes.io/name: rdp-services
    app.kubernetes.io/component: rdp
  ports:
  - port: 8090
    targetPort: 8090
    name: server-manager
  - port: 8091
    targetPort: 8091
    name: xrdp
  - port: 8092
    targetPort: 8092
    name: session-controller
  - port: 8093
    targetPort: 8093
    name: resource-monitor
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdp-data-pvc
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-services
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xrdp-config
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-services
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lucid-blockchain
data:
  xrdp.ini: |
    [globals]
    bitmap_cache=true
    bitmap_compression=true
    port=3389
    crypt_level=low
    channel_code=1
    max_bpp=24
    [xrdp1]
    name=sesman
    lib=libxup.so
    username=ask
    password=ask
    ip=127.0.0.1
    port=-1
