apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucid-rdp-server-manager
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-server-manager
    app.kubernetes.io/component: rdp
    app.kubernetes.io/part-of: lucid-blockchain
    lucid.service: rdp-server-manager
    lucid.type: application
    lucid.platform: arm64
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rdp-server-manager
      app.kubernetes.io/component: rdp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rdp-server-manager
        app.kubernetes.io/component: rdp
        app.kubernetes.io/part-of: lucid-blockchain
        lucid.service: rdp-server-manager
        lucid.type: application
        lucid.platform: arm64
    spec:
      hostname: lucid-rdp-server-manager
      containers:
      - name: rdp-server-manager
        image: pickme/lucid-rdp-server-manager:latest-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: manager
        - containerPort: 8090
          name: api
        env:
        - name: LUCID_ENV
          value: "production"
        - name: LUCID_PLATFORM
          value: "arm64"
        - name: PROJECT_ROOT
          value: "/mnt/myssd/Lucid/Lucid"
        - name: SERVICE_NAME
          value: "rdp-server-manager"
        - name: RDP_SERVER_MANAGER_PORT
          value: "8081"
        - name: RDP_SERVER_MANAGER_URL
          value: "http://lucid-rdp-server-manager:8081"
        - name: RDP_SERVER_MANAGER_HOST
          value: "172.20.0.21"
        - name: MONGODB_URI
          value: "mongodb://lucid:$(MONGODB_PASSWORD)@mongodb-service:27017/lucid?authSource=admin"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MONGODB_PASSWORD
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: REDIS_PASSWORD
        - name: API_GATEWAY_URL
          value: "http://lucid-api-gateway:8080"
        - name: RDP_PORT_RANGE_START
          value: "13389"
        - name: RDP_PORT_RANGE_END
          value: "14389"
        - name: MAX_CONCURRENT_SESSIONS
          value: "100"
        - name: SESSION_TIMEOUT
          value: "3600"
        volumeMounts:
        - name: rdp-config
          mountPath: /app/config
        - name: rdp-data
          mountPath: /data/rdp
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: rdp-config
        configMap:
          name: rdp-services-config
      - name: rdp-data
        persistentVolumeClaim:
          claimName: rdp-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lucid-rdp-server-manager
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-server-manager
    app.kubernetes.io/component: rdp
    app.kubernetes.io/part-of: lucid-blockchain
    lucid.service: rdp-server-manager
    lucid.type: application
    lucid.platform: arm64
spec:
  selector:
    app.kubernetes.io/name: rdp-server-manager
    app.kubernetes.io/component: rdp
  ports:
  - port: 8081
    targetPort: 8081
    name: manager
  - port: 8090
    targetPort: 8090
    name: api
  type: ClusterIP
  clusterIP: 172.20.0.21
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdp-data-pvc
  namespace: lucid-system
  labels:
    app.kubernetes.io/name: rdp-server-manager
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: lucid-blockchain
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
      